### ISSUE TITLE
Arabictoons is no longer working.

### ISSUE THREAD

**Issue by abc44** [ithrinet/xbmc-addons-repo#1]
Hi @ithrinet ,

I managed to install [arabictoons addon](https://github.com/ithrinet/xbmc-addons-repo/tree/master/plugin.video.ithri.arabic-toons) everything is working ok, but when it's the time to stream videos it doesn't work just load and load, and hang at last.

no video is displayed.

**Comment by ithrinet** [comment]
Hello,
now everything works fine.
